ad/urls.py
from django.urls import path
from . import views

app_name = 'ad'

urlpatterns = [
    path('', views.AllAdListView.as_view(), name='all_ad_list'),
    path('job/', views.JobListView.as_view(), name='job_list'),
    path('sale/', views.SaleListView.as_view(), name='sale_list'),
    path('rental/', views.RentalListView.as_view(), name='rental_list'),
    path('service/', views.ServiceListView.as_view(), name='service_list'),
    path('event/', views.EventListView.as_view(), name='event_list'),
    path('class/', views.ClassListView.as_view(), name='class_list'),
    path('ad/', views.AdListView.as_view(), name='ad_list'),
    path('ad/<str:adtype>/', views.AdCreateView.as_view(), name='create_ad'),
    path('ad/<str:adtype>/<int:pk>/', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/<str:adtype>/<int:pk>/update/', views.AdUpdateView.as_view(), name='ad_update'),
    path('ad/<str:adtype>/<int:pk>/delete/', views.AdDeleteView.as_view(), name='ad_delete'),
    path('<str:adtype>/comment/<int:pk>/edit/', views.EditCommentView.as_view(), name='edit_comment'),
    path('<str:adtype>/<int:adpk>/comment/<int:pk>/delete/', views.DeleteCommentView.as_view(), name='delete_comment'),
]

classifieds/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ad.urls',namespace='ad')),
    path('account/', include('account.urls', namespace='account')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ad/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from taggit.managers import TaggableManager
from django.utils import timezone
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

class AdInfo(models.Model):
    title = models.CharField(
        max_length=255,
    )
    description = models.TextField()
    tags = TaggableManager()
    
    def __str__(self):
        return self.title

    class Meta:
        abstract = True

class ContactInfo(models.Model):
    email = models.EmailField()
    show_email = models.BooleanField(default=True)
    phone = models.CharField(
        max_length=15,
        blank=True,
    )
    show_phone = models.BooleanField(default=False)

    class Meta:
        abstract = True

class AddressInfo(models.Model):
    location = models.CharField(
        max_length=255,
    )
    postal_code = models.CharField(
        max_length=20,
    )
    class Meta:
        abstract = True

class JobAd(AdInfo, ContactInfo, AddressInfo):
    CATEGORY_CHOICES = [
        ('FT', 'Full Time'),
        ('PT', 'Part Time'),
        ('IN', 'Internship'),
    ]
    category = models.CharField(
        max_length=2,
        choices=CATEGORY_CHOICES,
        default='FT',
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='jobads')
    salary = models.PositiveIntegerField()

class RentalAd(AdInfo, ContactInfo):
    CATEGORY_CHOICES = [
        ('FT', 'Flat'),
        ('PT', 'Furniture'),
        ('IN', 'Electronics'),
        ('VH', 'Vehicals'),
    ]
    category = models.CharField(
        max_length=2,
        choices=CATEGORY_CHOICES,
        default='FT',
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='rentalads')
    charge = models.PositiveIntegerField()
    PERIOD_CHOICES = [
        ('M', 'Month'),
        ('D', 'Day'),
        ('Y', 'Year'),
    ]
    period = models.CharField(
        max_length=1,
        choices=PERIOD_CHOICES,
        default='D',
    )

class SaleAd(AdInfo):
    CATEGORY_CHOICES = [
        ('EL', 'Electronics'),
        ('FU', 'Furniture'),
        ('BE', 'Beauty'),
        ('JW', 'Jwellary'),
        ('GR', 'Grocery'),
        ('BK', 'Books'),
        ('FA', 'Fashion'),
    ]
    category = models.CharField(
        max_length=2,
        choices=CATEGORY_CHOICES,
        default='FA',
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='saleads')
    price = models.PositiveIntegerField()
    
class ServiceAd(AdInfo, ContactInfo):
    CATEGORY_CHOICES = [
        ('IN', 'Insurance'),
        ('CT', 'Contruction'),
        ('LE', 'Legal'),
        ('WM', 'Waste Management'),
        ('GR', 'Gadget Repairing'),
    ]
    category = models.CharField(
        max_length=2,
        choices=CATEGORY_CHOICES,
        default='IN',
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='serviceads')
    price = models.PositiveIntegerField()
    
class EventAd(AdInfo, ContactInfo, AddressInfo):
    CATEGORY_CHOICES = [
        ('FE', 'Festival'),
        ('SE', 'Seminar'),
        ('SP', 'Sports Event'),
        ('MO', 'Modeling'),
    ]
    category = models.CharField(
        max_length=2,
        choices=CATEGORY_CHOICES,
        default='FE',
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='eventads')
    price = models.PositiveIntegerField()
    start_date = models.DateTimeField(default=datetime.datetime.now)
    end_date = models.DateTimeField(default=datetime.datetime.now)

class ClassAd(AdInfo, ContactInfo, AddressInfo):
    CATEGORY_CHOICES = [
        ('DA', 'Daily'),
        ('WE', 'Weekend'),
        ('WO', 'Workshop'),
        ('WO', 'Weekdays'),
    ]
    category = models.CharField(
        max_length=2,
        choices=CATEGORY_CHOICES,
        default='DA',
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='classads')
    fees = models.PositiveIntegerField()

class Message(models.Model):
    message=models.TextField(default='')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')
    created_at = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='messages', default=1)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    ad = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return f"Message by {self.user} on {self.created_at}"
     
class AdImage(models.Model):
    image = models.ImageField(upload_to='images/')
    
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, default=1)
    object_id = models.PositiveIntegerField(default=1)
    ad = GenericForeignKey('content_type', 'object_id')
    
    def __str__(self):
        return f"Image for {self.ad or 'unassociated image'}"

ad/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from .forms import JobAdForm, SaleAdForm, RentalAdForm, ServiceAdForm, EventAdForm, ClassAdForm, MessageForm
from .models import JobAd, RentalAd, SaleAd, ServiceAd, EventAd, ClassAd, Message, AdImage
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic import UpdateView, DeleteView, ListView
from django.http import Http404
from django.shortcuts import redirect
from django.contrib.contenttypes.models import ContentType
from django.forms import modelformset_factory

class ModelMappingMixin:
    model_mapping = {
        'job': JobAd,
        'sale': SaleAd,
        'rental': RentalAd,
        'for_sale': SaleAd,
        'service': ServiceAd,
        'event': EventAd,
        'class': ClassAd,
    }
    form_mapping = {
        'job': JobAdForm,
        'sale': SaleAdForm,
        'rental': RentalAdForm,
        'for_sale': SaleAdForm,
        'service': ServiceAdForm,
        'event': EventAdForm,
        'class': ClassAdForm,
    }

    def get_model(self):
        adtype = self.kwargs['adtype']
        model = self.model_mapping.get(adtype)
        if not model:
            raise Http404(f"No model found for ad type: {adtype}")
        return model

    def get_form_class(self):
        adtype = self.kwargs['adtype']
        return self.form_mapping.get(adtype)

    def get_queryset(self):
        model = self.get_model()
        return model.objects.filter(owner=self.request.user)

class AdListView(LoginRequiredMixin, TemplateView):
    template_name = 'ad/ad_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['jobs'] = JobAd.objects.filter(owner=self.request.user)
        context['rentals'] = RentalAd.objects.filter(owner=self.request.user)
        context['sales'] = SaleAd.objects.filter(owner=self.request.user)
        context['services'] = ServiceAd.objects.filter(owner=self.request.user)
        context['events'] = EventAd.objects.filter(owner=self.request.user)
        context['classes'] = ClassAd.objects.filter(owner=self.request.user)

        return context

class AdImagesMixin:
    def get_formset(self,queryset):
        AdImageFormSet = modelformset_factory(AdImage, fields=('image',), extra=4, can_delete=True)
        return AdImageFormSet(self.request.POST or None, self.request.FILES or None, queryset=queryset)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['formset'] = self.get_formset()
        return context
    
    def form_valid(self, form):
        form.instance.owner = self.request.user
        ad = form.save()
        adtype = self.kwargs['adtype']
        formset = self.get_formset()
        if formset.is_valid():
            for form in formset.cleaned_data:
                if form:
                    image = form['image']
                    content_type = ContentType.objects.get_for_model(ad)
                    object_id = ad.id
                    AdImage.objects.create(ad=ad, image=image, content_type=content_type,object_id=object_id)
        messages.success(self.request, 'Ad created successfully!')
        return redirect(self.success_url)
    
class AdCreateView(LoginRequiredMixin, AdImagesMixin,ModelMappingMixin,CreateView):
    template_name = 'ad/ad_form.html'
    success_url = reverse_lazy('ad:ad_list')
                   
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['adtype'] = self.kwargs['adtype']
        return kwargs

    def get_model(self):
        adtype = self.kwargs['adtype']
        return self.model_mapping.get(adtype)

    def get_form_class(self):
        adtype = self.kwargs['adtype']
        return self.form_mapping.get(adtype)

    def get_queryset(self):
        return self.get_model().objects.all()
    
    def get_formset(self):
        queryset = AdImage.objects.none()
        return super().get_formset(queryset)
    
class AdDetailView(LoginRequiredMixin, DetailView, ModelMappingMixin):
    template_name = 'ad/ad_detail.html'
    context_object_name = 'ad'
    login_url = '/account/login' 

    def get_model(self):
        adtype = self.kwargs['adtype']
        model = self.model_mapping.get(adtype)
        if not model:
            raise Http404(f"No model found for ad type: {adtype}")
        return model
    
    def get_queryset(self):
        model = self.get_model()
        return model.objects.all()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ad = self.get_object()
        adtype = self.kwargs['adtype']

        if ad.owner != self.request.user:
            context['comments'] = Message.objects.filter(
                content_type__model=adtype+'ad',
                object_id=ad.id,
                user=self.request.user
            )
        else:
            context['comments'] = Message.objects.filter(
                content_type__model=adtype+'ad',
                object_id=ad.id
            ).exclude(user=self.request.user)

        context['images'] = AdImage.objects.filter(
                content_type__model=adtype+'ad',
                object_id=ad.id
            )
        context['ad_type'] = adtype
        context['form'] = MessageForm()

        return context
    
    def post(self, request, *args, **kwargs):
        ad = self.get_object()
        adtype = self.kwargs['adtype']
        pk = self.kwargs['pk']
        form = MessageForm(request.POST)
        
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.ad = ad
            new_comment.user = request.user
            new_comment.content_type = ContentType.objects.get_for_model(ad)
            new_comment.object_id = ad.id
            new_comment.save()
            return redirect('ad:ad_detail', adtype=adtype, pk=pk)
        
        return self.get(request, *args, **kwargs)
      
class AdUpdateView(LoginRequiredMixin, AdImagesMixin, ModelMappingMixin, UpdateView):
    template_name = 'ad/ad_form.html'
    context_object_name = 'ad'
    success_url = reverse_lazy('ad:ad_list')

    def get_success_url(self):
        adtype = self.kwargs['adtype']
        return reverse_lazy('ad:ad_detail', kwargs={'adtype': adtype, 'pk': self.object.pk})
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_update'] = True
        return context
    
    def get_formset(self):
        adtype = self.kwargs['adtype']
        queryset=AdImage.objects.filter(content_type__model=adtype+'ad',
                object_id=self.object.id)
        return super().get_formset(queryset)
    
class AdDeleteView(LoginRequiredMixin, ModelMappingMixin, DeleteView):
    template_name = 'ad/ad_delete.html'
    context_object_name = 'ad'
    
    def get_success_url(self):
        return reverse_lazy('ad:ad_list')

    def delete(self, request, *args, **kwargs):
        response = super().delete(request, *args, **kwargs)
        messages.success(request, "Ad deleted successfully!")
        return response
    
class BaseListView(ListView):
    template_name="ad/adtype_list.html"
    context_object_name = 'ads'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        job_ad_content_type = ContentType.objects.get_for_model(self.model)
        
        all_images = AdImage.objects.filter(content_type=job_ad_content_type)
        
        images_dict = {}
        for image in all_images:
            if image.object_id not in images_dict:
               images_dict[image.object_id]=image
        
        context['images_dict'] = images_dict
        return context
    

class JobListView(BaseListView):
    model = JobAd

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ad_type'] = 'job'
        return context

class SaleListView(BaseListView):
    model = SaleAd
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ad_type'] = 'sale'
        return context

class RentalListView(BaseListView):
    model = RentalAd

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ad_type'] = 'rental'
        return context

class ServiceListView(BaseListView):
    model = ServiceAd
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ad_type'] = 'service'
        return context

class EventListView(BaseListView):
    model = EventAd
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ad_type'] = 'event'
        return context

class ClassListView(BaseListView):
    model = ClassAd
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ad_type'] = 'class'
        return context

class AllAdListView(TemplateView):
    template_name = 'ad/all_list.html'

    def get_images_for_model(self,model):
        all_images = AdImage.objects.filter(content_type=ContentType.objects.get_for_model(model))#,object_id__in=context['jobs'])
        print(all_images)
        images_dict = {}
        for image in all_images:
            if image.object_id not in images_dict:
               images_dict[image.object_id]=image
            print(image.id)
        return images_dict

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['jobs'] = JobAd.objects.all()[:4]
        context['jobimages']=self.get_images_for_model(JobAd)

ad/templates/includes/card.html
{% load static %}

<div class="col-md-4">
    <div class="card mb-4">
        {% with image_path="img/"|add:ad_type|add:"/image.jpg" %}
        {% for key, value in images_dict.items%}
            {% if key == item.id %}
            <img src="{{ value.image.url }}" class="card-img-top-{{ad_type}}-{{item.id}}" alt="{{ item.title }}" >
            {% endif%}
        {% endfor%}
        <img src="{% static image_path %}" class="card-img-top-{{ad_type}}-{{item.id}}" alt="{{ item.title }}" style="display:none;">
        {% endwith %}
        <div class="card-body">
            <h5 class="card-title">{{ item.title|capfirst }}</h5>
            <p class="card-text">{{ item.get_category_display }}</p>
        </div>
        <button type='button' class="detail-button"><a href="{% url 'ad:ad_detail' ad_type item.id %}">View Details</a></button>
    </div>
</div>
{% with ele=item.id%}
<script>
    document.getElementsByClassName('card-img-top-{{ad_type}}-{{item.id}}')[0].style.display='block';
</script>
{% endwith %}

ad/templates/includes/forms.html
{% load widget_tweaks %}

{% for field in form %}
    <div class="form-group">
      {{ field.label_tag }}

      {% if form.is_bound %}
        {% if field.errors %}

          {% render_field field class="form-control is-invalid" %}
          {% for error in field.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}

        {% else %}
          {% render_field field class="form-control is-valid" %}
        {% endif %}
      {% else %}
        {% render_field field class="form-control" %}
      {% endif %}

      {% if field.help_text %}
        <small class="form-text text-muted">
          {{ field.help_text }}
        </small>
      {% endif %}
    </div>
  {% endfor %}

ad/templates/includes/table.html
<table class="styled-table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Category</th>
            <th>Description</th>
            {% if ads.first.price%}
              <th>Price</th>
            {% elif ads.first.fees %}
              <th>Fees</th>
            {% elif ads.first.salary%}
              <th>Salary</th>
            {% else %}
              <th>Charges</th>
              <th>Period</th>
            {% endif %}
            <th>Tags</th>
            {% if ads.first.location %}
              <th>Location</th>
              <th>Postal Code</th>
            {% endif%}
            {% if ads.first.email %}
              <th>Email</th>
              <th>Phone</th>
            {% endif %}
            {% if ads.first.start_date %}
              <th>Start Date</th>
            {% endif %}
            {% if ads.first.end_date %}
              <th>End Date</th>
            {% endif %}
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for ad in ads %}
            <tr>
                <td><a href="{% url 'ad:ad_detail' adtype ad.id %}">{{ ad.title }}</a></td>
                <td>{{ ad.category }}</td>
                <td>{{ ad.description|truncatechars:50 }}</td>
                {% if ad.price %}
                  <td>Rs. {{ ad.price }}</td>
                {% elif ad.salary %}
                  <td>Rs. {{ ad.salary }}</td>
                {% elif ad.fees%}
                  <td>Rs. {{ ad.fees }}</td>
                {% else %}
                  <td>Rs. {{ ad.charge }}</td>
                  <td>{{ ad.period }}</td>
                {% endif %}
                <td>
                  {% for tag in ad.tags.all %}
                  <span>{{ tag.name }}</span>
                  {% empty %}
                  <span> - </span>
                  {% endfor %}
                </td>
                {% if ad.location%}
                  <td>{{ ad.location }}</td>
                  <td>{{ ad.postal_code }}</td>
                {% endif %}
                {% if ad.email %}
                  <td>{{ ad.email }}</td>
                  <td>{{ ad.phone }}</td>
                {% endif%}
                {% if ad.start_date%}
                  <td>{{ ad.start_date }}</td>
                  <td>{{ ad.end_date }}</td>
                {% endif%}
                <td>
                    <a href="{% url 'ad:ad_update' adtype ad.id %}">
                      <button type="button" class="edit-button button">Edit</button>
                    </a>
                    <a href="{% url 'ad:ad_delete' adtype ad.id %}">
                      <button type="button" class="delete-button button">Delete</button>
                    </a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>