ad/urls.py
from django.urls import path
from . import views

app_name = 'ad'

urlpatterns = [
    path('', views.AllAdListView.as_view(), name='all_ad_list'),
    path('job/', views.JobListView.as_view(), name='job_list'),
    path('sale/', views.SaleListView.as_view(), name='sale_list'),
    path('rental/', views.RentalListView.as_view(), name='rental_list'),
    path('service/', views.ServiceListView.as_view(), name='service_list'),
    path('event/', views.EventListView.as_view(), name='event_list'),
    path('class/', views.ClassListView.as_view(), name='class_list'),
    path('ad/', views.AdListView.as_view(), name='ad_list'),
    path('ad/<str:adtype>/', views.AdCreateView.as_view(), name='create_ad'),
    path('ad/<str:adtype>/<int:pk>/', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/<str:adtype>/<int:pk>/update/', views.AdUpdateView.as_view(), name='ad_update'),
    path('ad/<str:adtype>/<int:pk>/delete/', views.AdDeleteView.as_view(), name='ad_delete'),
    path('<str:adtype>/comment/<int:pk>/edit/', views.EditCommentView.as_view(), name='edit_comment'),
    path('<str:adtype>/<int:adpk>/comment/<int:pk>/delete/', views.DeleteCommentView.as_view(), name='delete_comment'),
]

classifieds/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ad.urls',namespace='ad')),
    path('account/', include('account.urls', namespace='account')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ad/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from taggit.managers import TaggableManager
from django.utils import timezone
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

class AdInfo(models.Model):
    title = models.CharField(
        max_length=255,
    )
    description = models.TextField()
    tags = TaggableManager()
    
    def __str__(self):
        return self.title

    class Meta:
        abstract = True

class ContactInfo(models.Model):
    email = models.EmailField()
    show_email = models.BooleanField(default=True)
    phone = models.CharField(
        max_length=15,
        blank=True,
    )
    show_phone = models.BooleanField(default=False)

    class Meta:
        abstract = True

class AddressInfo(models.Model):
    location = models.CharField(
        max_length=255,
    )
    postal_code = models.CharField(
        max_length=20,
    )
    class Meta:
        abstract = True

class JobAd(AdInfo, ContactInfo, AddressInfo):
    CATEGORY_CHOICES = [
        ('FT', 'Full Time'),
        ('PT', 'Part Time'),
        ('IN', 'Internship'),
    ]
    category = models.CharField(
        max_length=2,
        choices=CATEGORY_CHOICES,
        default='FT',
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='jobads')
    salary = models.PositiveIntegerField()

class RentalAd(AdInfo, ContactInfo):
    CATEGORY_CHOICES = [
        ('FT', 'Flat'),
        ('PT', 'Furniture'),
        ('IN', 'Electronics'),
        ('VH', 'Vehicals'),
    ]
    category = models.CharField(
        max_length=2,
        choices=CATEGORY_CHOICES,
        default='FT',
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='rentalads')
    charge = models.PositiveIntegerField()
    PERIOD_CHOICES = [
        ('M', 'Month'),
        ('D', 'Day'),
        ('Y', 'Year'),
    ]
    period = models.CharField(
        max_length=1,
        choices=PERIOD_CHOICES,
        default='D',
    )

class SaleAd(AdInfo):
    CATEGORY_CHOICES = [
        ('EL', 'Electronics'),
        ('FU', 'Furniture'),
        ('BE', 'Beauty'),
        ('JW', 'Jwellary'),
        ('GR', 'Grocery'),
        ('BK', 'Books'),
        ('FA', 'Fashion'),
    ]
    category = models.CharField(
        max_length=2,
        choices=CATEGORY_CHOICES,
        default='FA',
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='saleads')
    price = models.PositiveIntegerField()
    
class ServiceAd(AdInfo, ContactInfo):
    CATEGORY_CHOICES = [
        ('IN', 'Insurance'),
        ('CT', 'Contruction'),
        ('LE', 'Legal'),
        ('WM', 'Waste Management'),
        ('GR', 'Gadget Repairing'),
    ]
    category = models.CharField(
        max_length=2,
        choices=CATEGORY_CHOICES,
        default='IN',
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='serviceads')
    price = models.PositiveIntegerField()
    
class EventAd(AdInfo, ContactInfo, AddressInfo):
    CATEGORY_CHOICES = [
        ('FE', 'Festival'),
        ('SE', 'Seminar'),
        ('SP', 'Sports Event'),
        ('MO', 'Modeling'),
    ]
    category = models.CharField(
        max_length=2,
        choices=CATEGORY_CHOICES,
        default='FE',
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='eventads')
    price = models.PositiveIntegerField()
    start_date = models.DateTimeField(default=datetime.datetime.now)
    end_date = models.DateTimeField(default=datetime.datetime.now)

class ClassAd(AdInfo, ContactInfo, AddressInfo):
    CATEGORY_CHOICES = [
        ('DA', 'Daily'),
        ('WE', 'Weekend'),
        ('WO', 'Workshop'),
        ('WO', 'Weekdays'),
    ]
    category = models.CharField(
        max_length=2,
        choices=CATEGORY_CHOICES,
        default='DA',
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='classads')
    fees = models.PositiveIntegerField()

class Message(models.Model):
    message=models.TextField(default='')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')
    created_at = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='messages', default=1)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    ad = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return f"Message by {self.user} on {self.created_at}"
     
class AdImage(models.Model):
    image = models.ImageField(upload_to='images/')
    
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, default=1)
    object_id = models.PositiveIntegerField(default=1)
    ad = GenericForeignKey('content_type', 'object_id')
    
    def __str__(self):
        return f"Image for {self.ad or 'unassociated image'}"

ad/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from .forms import JobAdForm, SaleAdForm, RentalAdForm, ServiceAdForm, EventAdForm, ClassAdForm, MessageForm
from .models import JobAd, RentalAd, SaleAd, ServiceAd, EventAd, ClassAd, Message, AdImage
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic import UpdateView, DeleteView, ListView
from django.http import Http404
from django.shortcuts import redirect
from django.contrib.contenttypes.models import ContentType
from django.forms import modelformset_factory

class ModelMappingMixin:
    model_mapping = {
        'job': JobAd,
        'sale': SaleAd,
        'rental': RentalAd,
        'for_sale': SaleAd,
        'service': ServiceAd,
        'event': EventAd,
        'class': ClassAd,
    }
    form_mapping = {
        'job': JobAdForm,
        'sale': SaleAdForm,
        'rental': RentalAdForm,
        'for_sale': SaleAdForm,
        'service': ServiceAdForm,
        'event': EventAdForm,
        'class': ClassAdForm,
    }

    def get_model(self):
        adtype = self.kwargs['adtype']
        model = self.model_mapping.get(adtype)
        if not model:
            raise Http404(f"No model found for ad type: {adtype}")
        return model

    def get_form_class(self):
        adtype = self.kwargs['adtype']
        return self.form_mapping.get(adtype)

    def get_queryset(self):
        model = self.get_model()
        return model.objects.filter(owner=self.request.user)

class AdListView(LoginRequiredMixin, TemplateView):
    template_name = 'ad/ad_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['jobs'] = JobAd.objects.filter(owner=self.request.user)
        context['rentals'] = RentalAd.objects.filter(owner=self.request.user)
        context['sales'] = SaleAd.objects.filter(owner=self.request.user)
        context['services'] = ServiceAd.objects.filter(owner=self.request.user)
        context['events'] = EventAd.objects.filter(owner=self.request.user)
        context['classes'] = ClassAd.objects.filter(owner=self.request.user)

        return context

class AdImagesMixin:
    def get_formset(self,queryset):
        AdImageFormSet = modelformset_factory(AdImage, fields=('image',), extra=4, can_delete=True)
        return AdImageFormSet(self.request.POST or None, self.request.FILES or None, queryset=queryset)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['formset'] = self.get_formset()
        return context
    
    def form_valid(self, form):
        form.instance.owner = self.request.user
        ad = form.save()
        adtype = self.kwargs['adtype']
        formset = self.get_formset()
        if formset.is_valid():
            for form in formset.cleaned_data:
                if form:
                    image = form['image']
                    content_type = ContentType.objects.get_for_model(ad)
                    object_id = ad.id
                    AdImage.objects.create(ad=ad, image=image, content_type=content_type,object_id=object_id)
        messages.success(self.request, 'Ad created successfully!')
        return redirect(self.success_url)
    
class AdCreateView(LoginRequiredMixin, AdImagesMixin,ModelMappingMixin,CreateView):
    template_name = 'ad/ad_form.html'
    success_url = reverse_lazy('ad:ad_list')
                   
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['adtype'] = self.kwargs['adtype']
        return kwargs

    def get_model(self):
        adtype = self.kwargs['adtype']
        return self.model_mapping.get(adtype)

    def get_form_class(self):
        adtype = self.kwargs['adtype']
        return self.form_mapping.get(adtype)

    def get_queryset(self):
        return self.get_model().objects.all()
    
    def get_formset(self):
        queryset = AdImage.objects.none()
        return super().get_formset(queryset)
    
class AdDetailView(LoginRequiredMixin, DetailView, ModelMappingMixin):
    template_name = 'ad/ad_detail.html'
    context_object_name = 'ad'
    login_url = '/account/login' 

    def get_model(self):
        adtype = self.kwargs['adtype']
        model = self.model_mapping.get(adtype)
        if not model:
            raise Http404(f"No model found for ad type: {adtype}")
        return model
    
    def get_queryset(self):
        model = self.get_model()
        return model.objects.all()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ad = self.get_object()
        adtype = self.kwargs['adtype']

        if ad.owner != self.request.user:
            context['comments'] = Message.objects.filter(
                content_type__model=adtype+'ad',
                object_id=ad.id,
                user=self.request.user
            )
        else:
            context['comments'] = Message.objects.filter(
                content_type__model=adtype+'ad',
                object_id=ad.id
            ).exclude(user=self.request.user)

        context['images'] = AdImage.objects.filter(
                content_type__model=adtype+'ad',
                object_id=ad.id
            )
        context['ad_type'] = adtype
        context['form'] = MessageForm()

        return context
    
    def post(self, request, *args, **kwargs):
        ad = self.get_object()
        adtype = self.kwargs['adtype']
        pk = self.kwargs['pk']
        form = MessageForm(request.POST)
        
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.ad = ad
            new_comment.user = request.user
            new_comment.content_type = ContentType.objects.get_for_model(ad)
            new_comment.object_id = ad.id
            new_comment.save()
            return redirect('ad:ad_detail', adtype=adtype, pk=pk)
        
        return self.get(request, *args, **kwargs)
      
class AdUpdateView(LoginRequiredMixin, AdImagesMixin, ModelMappingMixin, UpdateView):
    template_name = 'ad/ad_form.html'
    context_object_name = 'ad'
    success_url = reverse_lazy('ad:ad_list')

    def get_success_url(self):
        adtype = self.kwargs['adtype']
        return reverse_lazy('ad:ad_detail', kwargs={'adtype': adtype, 'pk': self.object.pk})
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_update'] = True
        return context
    
    def get_formset(self):
        adtype = self.kwargs['adtype']
        queryset=AdImage.objects.filter(content_type__model=adtype+'ad',
                object_id=self.object.id)
        return super().get_formset(queryset)
    
class AdDeleteView(LoginRequiredMixin, ModelMappingMixin, DeleteView):
    template_name = 'ad/ad_delete.html'
    context_object_name = 'ad'
    
    def get_success_url(self):
        return reverse_lazy('ad:ad_list')

    def delete(self, request, *args, **kwargs):
        response = super().delete(request, *args, **kwargs)
        messages.success(request, "Ad deleted successfully!")
        return response
    
class BaseListView(ListView):
    template_name="ad/adtype_list.html"
    context_object_name = 'ads'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        job_ad_content_type = ContentType.objects.get_for_model(self.model)
        
        all_images = AdImage.objects.filter(content_type=job_ad_content_type)
        
        images_dict = {}
        for image in all_images:
            if image.object_id not in images_dict:
               images_dict[image.object_id]=image
        
        context['images_dict'] = images_dict
        return context
    

class JobListView(BaseListView):
    model = JobAd

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ad_type'] = 'job'
        return context

class SaleListView(BaseListView):
    model = SaleAd
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ad_type'] = 'sale'
        return context

class RentalListView(BaseListView):
    model = RentalAd

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ad_type'] = 'rental'
        return context

class ServiceListView(BaseListView):
    model = ServiceAd
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ad_type'] = 'service'
        return context

class EventListView(BaseListView):
    model = EventAd
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ad_type'] = 'event'
        return context

class ClassListView(BaseListView):
    model = ClassAd
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ad_type'] = 'class'
        return context

class AllAdListView(TemplateView):
    template_name = 'ad/all_list.html'

    def get_images_for_model(self,model):
        all_images = AdImage.objects.filter(content_type=ContentType.objects.get_for_model(model))#,object_id__in=context['jobs'])
        print(all_images)
        images_dict = {}
        for image in all_images:
            if image.object_id not in images_dict:
               images_dict[image.object_id]=image
            print(image.id)
        return images_dict

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['jobs'] = JobAd.objects.all()[:4]
        context['jobimages']=self.get_images_for_model(JobAd)

ad/templates/ad/ad_delete.html
{% extends 'base_post.html' %}

{% block content %}
  <h2>Confirm Delete</h2>
  <p>Are you sure you want to delete the ad "{{ ad.title }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="submit-button">Delete</button>
    <a href="{% url 'ad:ad_list' %}">Cancel</a>
  </form>
{% endblock %}

ad/templates/ad/ad_detail.html
{% extends "base.html" %}
{% load humanize %}
{% load static %}

{% block style%}
  <link href="{% static "css/detail.css" %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{% endblock %}

{% block content %}
<div class="ad-detail-container">
  <div class="ad-details">
    <div class="ad-image">
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          {% for image in images %}
          <div class="carousel-item {% if forloop.first %}active{% endif %}">
          <img src="{{ image.image.url }}" alt="Ad Image" width="450px" style="height: 350px">
          </div>
          {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
      {% if not images %}
        {% with image_path="img/"|add:ad_type|add:"/image.jpg" %}
          <img src="{% static image_path %}" alt="Ad Image" height="350px" width="450px">
        {% endwith %}
      {% endif %}
    </div>
    
    <div class="details">
      <h1 class='ad-title'>{{ ad.title|capfirst }}</h1>
      
      <div class="ad-description">
        <p>{{ ad.description }}</p>
      </div>
      
      <div class="ad-category">
        <p><strong>Category: </strong>{{ ad.get_category_display }}</p>
      </div>
      <br>
      <div class="ad-tags">
        <h3>Tags:</h3>
        <ul>
          {% for tag in ad.tags.all %}
          <li>{{ tag.name }}</li>
          {% empty %}
          <li>No tags available</li>
          {% endfor %}
        </ul>
      </div>
      <br>
      {% if ad.email %}
      <div class="ad-contact">
        <h3>Contact Information</h3>
        <p><strong>Email:</strong> <a href="mailto:{{ ad.email }}">{{ ad.email }}</a></p>
        <p><strong>Phone:</strong> <a href="tel:{{ ad.phone }}">{{ ad.phone }}</a></p>
      </div>
      {% endif %}
      
      {% if ad.location %}
      <div class="ad-location">
        <h3>Location</h3>
        <p><strong>Address:</strong> {{ ad.location }}</p>
        <p><strong>Postal Code:</strong> {{ ad.postal_code }}</p>
      </div>
      {% endif %}
      
      <div class="ad-salary">
        {% if ad.salary %}
        <p><strong>Salary:</strong> {{ ad.salary }}</p>
        {% elif ad.price %}
        <p><strong>Price:</strong> {{ ad.price }}</p>
        {% elif ad.fees %}
        <p><strong>Fees:</strong> {{ ad.fees }}</p>
        {% elif ad.charge %}
        <p><strong>Charge:</strong> {{ ad.charge }}</p>
        <p><strong>Charge for period:</strong> {{ ad.get_period_display }}</p>
        {% endif %}
      </div>
      
      {% if ad.start_date %}
      <h3>Event Time</h3>
      <p><strong>Start Time:</strong> {{ ad.start_date }}</p>
      <p><strong>End Time:</strong> {{ ad.end_date }}</p>
      {% endif %}
    </div>
  </div>
  <div class='comment-container'>
  {% for comment in comments %}
  <div style="margin-left: {{ comment.depth }}em;">
    <div style="display: flex;align-items: center; gap: 20px;"><p class="comment">{{ comment.message }}</p>
      {% if comment.user == request.user %}
    <div style="display: flex;align-items: center; gap: 20px;">
      <a href="{% url 'ad:edit_comment' ad_type comment.id %}">
        <button type="button" class="btn edit-button">Edit</button>
      </a>
      <a href="{% url 'ad:delete_comment' ad_type ad.id comment.id %}">
        <button type="button" class="btn delete-button">Delete</button>
      </a>
    </div>
    {% endif %}
  </div>
    <small>{{ comment.created_at|naturaltime }}</small>
    
    {% if ad.owner == request.user %}
    <a href="#" onclick="document.getElementById('reply-form-{{ comment.id }}').style.display='block'; return false;">Reply</a>
    {% endif %}
    
    <div id="reply-form-{{ comment.id }}" style="display:none; margin-left: 1em;">
      <form method="post" class="reply-form">
        {% csrf_token %}
        {{ form.message }}
        <input type="hidden" name="parent" value="{{ comment.id }}">
        <button type="submit" class="btn send-message">Post Reply</button>
      </form>
    </div>
    
    {% for reply in comment.replies.all %}
    <div>
      <p class="reply">{{ reply.message }}</p>
      <small class='reply-time'>{{ reply.created_at|naturaltime }}</small>
    </div>
    {% endfor %}
    
  </div>
  {% endfor %}
  
  {% if user != ad.owner %}
  <form method="post" class="message-form">
    {% csrf_token %}
    {{ form.message }}
    <button type="submit" class="btn send-message" style="height: 35px; padding: auto auto 7px; margin: 0px 0px 5px;">SEND MESSAGE</button>
  </form>
  {% endif %}
</div>
</div>
<div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{% endblock %}
  

ad/templates/ad/ad_form.html
{% extends "base_post.html" %}

{% load static %}

{% block style %}
<link href="{% static "css/form.css" %}" rel="stylesheet">
{% endblock%}
{% block content %}
<h1 class="heading">
    {% if is_update %}
        Update Ad
    {% else %}
        Create New Ad
    {% endif %}
</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include "includes/forms.html" %}
    {{ formset.management_form }}
    {% for form in formset %}
        {{ form.as_p }}
    {% endfor %}
    <button type="submit" class="submit-button">Save</button>
</form>
{% endblock %}

ad/templates/ad/ad_list.html
{% extends "base_post.html" %}

{% load static %}

{% block style %}
 <link href="{% static "css/table.css" %}" rel="stylesheet">
{% endblock%}

{% block content %}

<div class="nav-create-ad">
    <h2 class="heading">CREATE NEW ADS</h2>
    <div><a href="{% url 'ad:create_ad' 'job' %}">JOB</a></div>
    <div><a href="{% url 'ad:create_ad' 'rental' %}">RENTAL</a></div>
    <div><a href="{% url 'ad:create_ad' 'sale' %}">SALE</a></div>
    <div><a href="{% url 'ad:create_ad' 'service' %}">SERVICE</a></div>
    <div><a href="{% url 'ad:create_ad' 'event' %}">EVENT</a></div>
    <div><a href="{% url 'ad:create_ad' 'class' %}">CLASS</a></div>
</div>
<h1 class="heading">Ad List</h1>
    {% if jobs %}
      <div class="list-heading">JOBS</div>
      {% with ads=jobs adtype='job' %}
         {% include "includes/table.html" %}
      {% endwith %}
    {% endif %}
    {% if rentals %}
      <div class="list-heading">RENTALS</div>
      {% with ads=rentals adtype='rental' %}
         {% include "includes/table.html" %}
      {% endwith %}
    {% endif %}
    {% if sales %}
      <div class="list-heading">SALES</div>
      {% with ads=sales adtype='sale' %}
         {% include "includes/table.html" %}
      {% endwith %}
    {% endif %}
    {% if services %}
      <div class="list-heading">SERVICES</div>
      {% with ads=services adtype='service' %}
         {% include "includes/table.html" %}
      {% endwith %}
    {% endif %}
    {% if events %}
      <div class="list-heading">EVENTS</div>
      {% with ads=events adtype='event' %}
         {% include "includes/table.html" %}
      {% endwith %}
    {% endif %}
    {% if classes %}
      <div class="list-heading">CLASSES</div>
      {% with ads=classes adtype='class' %}
         {% include "includes/table.html" %}
      {% endwith %}
    {% endif %}
{% endblock %}

ad/templates/ad/adtype_list.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <ul class="list-group">
        {% for item in ads %}
            {% with adtype=ad_type%}
            {% include "includes/card.html" %}
            {% endwith %}
        {% empty %}
            <div class="unavailable">No ads available.</div>
        {% endfor %}
    </ul>
</div>
{% endblock %}

ad/templates/ad/all_list.html
{% extends "base.html" %}

{% block content %}
    <div class="list-heading">JOBS</div>
    <ul class="list-group">
        {% for item in jobs %}
            {% with ad_type='job' images_dict=jobimages%}
            {% include "includes/card.html" %}
            {% endwith %}
        {% empty %}
            <div class="unavailable">No ads available.</div>
        {% endfor %}
    </ul>
    <div class="list-heading">RENTALS</div>
    <ul class="list-group">
        {% for item in rentals %}
            {% with ad_type='rental' images_dict=rentalimages %}
            {% include "includes/card.html" %}
            {% endwith%}
        {% empty %}
            <div class="unavailable">No ads available.</div>
        {% endfor %}
    </ul>
    <div class="list-heading">SALES</div>
    <ul class="list-group">
        {% for item in sales %}
            {% with ad_type='sale' images_dict=saleimages %}
            {% include "includes/card.html" %}
            {% endwith %}
        {% empty %}
            <div class="unavailable">No ads available.</div>
        {% endfor %}
    </ul>
    <div class="list-heading">SERVICES</div>
    <ul class="list-group">
        {% for item in services %}
            {% with ad_type='service' images_dict=serviceimages %}
            {% include "includes/card.html" %}
            {% endwith %}
        {% empty %}
            <div class="unavailable">No ads available.</div>
        {% endfor %}
    </ul>
    <div class="list-heading">EVENTS</div>
    <ul class="list-group">
        {% for item in events %}
            {% with ad_type='event' images_dict=eventimages %}
            {% include "includes/card.html" %}
            {% endwith%}
        {% empty %}
            <div class="unavailable">No ads available.</div>
        {% endfor %}
    </ul>
    <div class="list-heading">CLASSES</div>
    <ul class="list-group">
        {% for item in classes %}
            {% with ad_type='class' images_dict=classimages %}
            {% include "includes/card.html" %}
            {% endwith %}
        {% empty %}
            <div class="unavailable">No ads available.</div>
        {% endfor %}
    </ul>
{% endblock %}