account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import SignUpView

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_reset/', 
         auth_views.PasswordResetView.as_view(template_name='account/password_reset_form.html',email_template_name='account/password_reset_email.html',success_url='/account/password_reset/done/'), 
         name='password_reset'),
    path('password_reset/done/', 
         auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'), 
         name='password_reset_done'),
    path('reset/done/', 
        auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), 
        name='password_reset_complete'),
    path('reset/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html', success_url='/account/reset/done/'), 
        name='password_reset_confirm'),
]

ad/urls.py
from django.urls import path
from . import views

app_name = 'ad'

urlpatterns = [
    path('', views.AllAdListView.as_view(), name='all_ad_list'),
    path('job/', views.JobListView.as_view(), name='job_list'),
    path('sale/', views.SaleListView.as_view(), name='sale_list'),
    path('rental/', views.RentalListView.as_view(), name='rental_list'),
    path('service/', views.ServiceListView.as_view(), name='service_list'),
    path('event/', views.EventListView.as_view(), name='event_list'),
    path('class/', views.ClassListView.as_view(), name='class_list'),
    path('ad/', views.AdListView.as_view(), name='ad_list'),
    path('ad/<str:adtype>/', views.AdCreateView.as_view(), name='create_ad'),
    path('ad/<str:adtype>/<int:pk>/', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/<str:adtype>/<int:pk>/update/', views.AdUpdateView.as_view(), name='ad_update'),
    path('ad/<str:adtype>/<int:pk>/delete/', views.AdDeleteView.as_view(), name='ad_delete'),
    path('<str:adtype>/comment/<int:pk>/edit/', views.EditCommentView.as_view(), name='edit_comment'),
    path('<str:adtype>/<int:adpk>/comment/<int:pk>/delete/', views.DeleteCommentView.as_view(), name='delete_comment'),
]

classifieds/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ad.urls',namespace='ad')),
    path('account/', include('account.urls', namespace='account')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path
from . import views

app_name = 'customer'

urlpatterns = [
    path('', views.AllAdListView.as_view(), name='all_ad_list'),
    path('job/', views.JobListView.as_view(), name='job_list'),
    path('sale/', views.SaleListView.as_view(), name='sale_list'),
    path('rental/', views.RentalListView.as_view(), name='rental_list'),
    path('service/', views.ServiceListView.as_view(), name='service_list'),
    path('event/', views.EventListView.as_view(), name='event_list'),
    path('class/', views.ClassListView.as_view(), name='class_list'),
]

customer/models.py
from django.db import models

# Create your models here.

customer/views.py
from django.views.generic import ListView, TemplateView
from ad.models import JobAd, RentalAd, SaleAd, ServiceAd, EventAd, ClassAd

class BaseListView(ListView):
    template_name = 'customer/list.html'
    context_object_name = 'ads'

class JobListView(BaseListView):
    model = JobAd

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ad_type'] = 'job'
        return context

class RentalListView(BaseListView):
    model = RentalAd

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ad_type'] = 'rental'
        return context

class SaleListView(BaseListView):
    model = SaleAd

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ad_type'] = 'sale'
        return context

class ServiceListView(BaseListView):
    model = ServiceAd

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ad_type'] = 'service'
        return context

class EventListView(BaseListView):
    model = EventAd

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ad_type'] = 'event'
        return context

class ClassListView(BaseListView):
    model = ClassAd

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ad_type'] = 'class'
        return context
    
class AllAdListView(TemplateView):
    template_name = 'customer/all_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['jobs'] = JobAd.objects.all()[:4]
        context['rentals'] = RentalAd.objects.all()[:4]
        context['sales'] = SaleAd.objects.all()[:4]
        context['services'] = ServiceAd.objects.all()[:4]
        context['events'] = EventAd.objects.all()[:4]
        context['classes'] = ClassAd.objects.all()[:4]

        return context

customer/templates/base_customer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ClassiFieds</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/card.css' %}" rel="stylesheet">
</head>
<body>
    <nav class="nav-bar">
       <h1>ClassiFieds</h1>
       <input type="text" placeholder="Search...">
       <div class="nav-auth-container">
            {% if user.is_authenticated %}  
                    {{ user.username }}
                    <form action="{% url 'account:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn logout-button">Logout</button>
                    </form>
                    <a href="{% url 'ad:ad_list' %}"><button type='button' class="btn sell-button">SELL</button></a> 
            {% else %}
                <a href="{% url 'account:login' %}"><button type='button' class="btn login-button">Log in</button>
                <a href="{% url 'account:signup' %}"><button type='button' class="btn signup-button">Sign up</button></a>
            {% endif %}

        </div>
       
    </nav>
    <div class="ad-type-container">
        <a href="{% url 'customer:all_ad_list'%}" class="{% if ad_type == False %}selected{% endif %}">All</a>
        <a href="{% url 'customer:sale_list'%}" class="{% if ad_type == 'sale' %}selected{% endif %}">Sale</a>
        <a href="{% url 'customer:job_list'%}" class="{% if ad_type == 'job' %}selected{% endif %}">Job</a>
        <a href="{% url 'customer:rental_list'%}" class="{% if ad_type == 'rental' %}selected{% endif %}">Rental</a>
        <a href="{% url 'customer:service_list'%}" class="{% if ad_type == 'service' %}selected{% endif %}">Service</a>
        <a href="{% url 'customer:event_list'%}" class="{% if ad_type == 'event' %}selected{% endif %}">Event</a>
        <a href="{% url 'customer:class_list'%}" class="{% if ad_type == 'class' %}selected{% endif %}">Class</a>
    </div>
    <div>
        
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>